### ISSUE TITLE
Support JSON output type(s)

### ISSUE THREAD

**Issue by ronichoudhury** [OpenGeoscience/girder_db_items#9]
- Proper JSON
- "JSON Array", i.e., the format of newline separated JSON objects used by `mongoimport`

**Comment by manthey** [comment]
The current 'list' and 'dict' formats are both well-formed JSON.  Are you are asking for a plain JSON array (the contents of the current dict output's `data` element)?  E.g.,
```
[{"town":"BOSTON","pop2000":"588957","pop1990":"574283"},{"town":"WORCESTER","pop2000":"172648","pop1990":"169759"},{"town":"SPRINGFIELD","pop2000":"152082","pop1990":"156983"}]
```

The 'JSON array' format would yield, in this case:
```
{"town":"BOSTON","pop2000":"588957","pop1990":"574283"}
{"town":"WORCESTER","pop2000":"172648","pop1990":"169759"}
{"town":"SPRINGFIELD","pop2000":"152082","pop1990":"156983"}
```

**Comment by manthey** [comment]
Added in PR #11.

**Comment by ronichoudhury** [comment]
My terminology was muddy. `mongoimport` has a flag `--jsonArray` which says the input should be an actual JSON-encoded array (i.e., with square brackets and commas between elements). I was referring to the newline separated format that `mongoimport` needs by default (without the `--jsonArray` flag). So your example above is what I was asking for. Apologies :-D

**Comment by manthey** [comment]
@ronichoudhury  Perhaps I've misnamed the new formats then.  We can output five formats now:
- `list`:
```
{"sort":[["pop2010",-1]],"datacount":3,"format":"list","fields":["town","pop1990","pop2000"],"limit":3,"offset":0,"data":[["BOSTON","574283","588957"],["WORCESTER","169759","172648"],["SPRINGFIELD","156983","152082"]],"columns":{"town":0,"pop2000":2,"pop1990":1}}
```
- `dict`: 
```
{"sort":[["pop2010",-1]],"datacount":3,"format":"dict","fields":["town","pop1990","pop2000"],"limit":3,"offset":0,"data":[{"town":"BOSTON","pop2000":"588957","pop1990":"574283"},{"town":"WORCESTER","pop2000":"172648","pop1990":"169759"},{"town":"SPRINGFIELD","pop2000":"152082","pop1990":"156983"}],"columns":{"town":0,"pop2000":2,"pop1990":1}}
```
- `csv`:
```
town,pop1990,pop2000
BOSTON,574283,588957
WORCESTER,169759,172648
SPRINGFIELD,156983,152082
```
- `json`:
```
[{"town":"BOSTON","pop2000":"588957","pop1990":"574283"},{"town":"WORCESTER","pop2000":"172648","pop1990":"169759"},{"town":"SPRINGFIELD","pop2000":"152082","pop1990":"156983"}]
```
- `jsonarray`:
```
{"town":"BOSTON","pop2000":"588957","pop1990":"574283"}
{"town":"WORCESTER","pop2000":"172648","pop1990":"169759"}
{"town":"SPRINGFIELD","pop2000":"152082","pop1990":"156983"}
```

The format I've called `json` is a JSON array.  The format called `jsonarray` has one row of data per line, with each row a stand-alone JSON document.

**Comment by ronichoudhury** [comment]
I think `json` is named correctly, but `jsonarray` is not. The Mongo documentation doesn't seem to have a name for this almost-JSON format it uses for export/import.

e.g., here is what the [`mongoexport` documentation](https://docs.mongodb.com/manual/reference/program/mongoexport/#cmdoption--jsonArray) has to say about it:

> By default mongoexport writes data using one JSON document for every MongoDB document.

`mongojson` might be an ok name for the format; maybe `jsonlines` is better.

**Comment by manthey** [comment]
I think I'll go with `jsonlines` (PR coming soon), as that is similar to what Elasticsearch's [logstash](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json_lines.html) calls it.

**Comment by ronichoudhury** [comment]
:+1:
